am/urls.py
from django.contrib.auth import views as auth_views
from django.urls import include, path, reverse_lazy
from django.views.generic import TemplateView
from rest_framework.routers import SimpleRouter

from am import views

app_name = 'am'

router = SimpleRouter()
router.register(r'classe', views.ClasseViewSet, 'classe')
# router.register(r'feuiller', views.FeuilleViewSetR, 'feuiller')
router.register(r'feuille', views.FeuilleViewSet, 'feuille')
router.register(r'latexmodel', views.LatexModelViewSet)
router.register(r'latexmodelpart', views.LatexModelPartViewSet)
router.register(r'question', views.QuestionViewSet, 'question')
router.register(r'question-posee', views.QuestionPoseeViewSet, 'question-posee')
router.register(r'seance', views.SeanceViewSet, 'seance')
router.register(r'seancer', views.SeanceViewSetR, 'seancer')
router.register(r'theme', views.ThemeViewSet, 'theme')

urlpatterns = [
    path('', TemplateView.as_view(template_name='index.html'), name='home'),
    path('password_reset/', auth_views.PasswordResetView.as_view(
        success_url=reverse_lazy('am:password_reset_done'),
    ),
         name='password_reset'
         ),
    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(success_url=reverse_lazy('am:password_reset_complete')),
         name='password_reset_confirm'
         ),
    path('', include('django.contrib.auth.urls')),
    path('signup/', views.SignUpView.as_view(), name='signup'),
    path('profile/', views.UserChangeView.as_view(), name='profile'),
    path('password/', auth_views.PasswordChangeView.as_view(
        template_name='registration/password_change.html',
        success_url='/am/profile/'
    ), name='change_password'),
    path('api/', include((router.urls, app_name))),
    path('api/annee_list/', views.AnneeView.as_view()),
]

config/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView


urlpatterns = [
    path("", RedirectView.as_view(url='am/')),
    path("am/", include('am.urls', namespace="am")),
    path("admin/", admin.site.urls),
]

templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Activités Mentales{% block title %}{% endblock%}</title>
    {% block head %}{% endblock%}
  </head>

  <body>
  {% block content %}
  {% endblock %}
  </body>
</html>

templates/home.html
{% extends 'base.html' %}

export default {
    namespaced: true,
    state,
    getters,
    actions,
    mutations
}
{% load render_bundle from webpack_loader %}
{% block title %}{% endblock %}

{% block content %}
<noscript>
    <strong>We're sorry but frontend doesn't work properly without JavaScript enabled. Please enable it to
        continue.</strong>
</noscript>
{% if not user.is_authenticated %}
<h1>Activités Mentales</h1>
<div>
    <p>Vous n'êtes pas connecté.</p>

    <a href="{% url 'am:login' %}">Connexion</a> |
    <a href="{% url 'am:signup' %}">Créer un compte</a>
</div>
<br>
<br>
<div>
    Bienvenu(e) sur le générateur de séance d'activités mentales (ou automatismes)<br>

    Si vous voulez simplement visiter, vous pouvez utiliser les identifiants suivants :
    <ul>
        <li>Utilisateur: Test</li>
        <li>Mot de passe: test</li>
    </ul>

    Sinon vous pouvez vous inscrire (totalement gratuit).<br>
    Vous pourrez ensuite ajouter vos classes et leur créer des séances d'activités mentales.
    <p>
        Le site est en pleine construction. Ce n'est pas encore beau mais c'est déjà fonctionnel.
        <br>
        Contact: <a href="mailto:guillaume.claus@ac-grenoble.fr">Guillaume Claus</a>
    </p>
</div>

{% else %}

<div id="app">
    <app></app>
</div>
<script>
    var username = "{{ user.username }}";
    var permissions = [];
    {% if perms.am.question_valider %}
    permissions.push('Validateur');
    {% endif %}
    {% if perms.am.change_latexmodel %}
    permissions.push('ChangeLatex');
    {% endif %}

</script>
{% render_bundle 'app' %}

{% endif %}
{% endblock %}